name: Ejecutar Puppeteer Manualmente

on:
  schedule:
    - cron: '0 15 * * 5' # Every Friday at 15:00 UTC
  workflow_dispatch:
    inputs:
      argumento:
        description: 'Argumento opcional para el script'
        required: false
        default: ''

jobs:
  run-puppeteer:
    runs-on: ubuntu-latest
    env:
      KEY_CLOUDFLARE: ${{ secrets.KEY_CLOUDFLARE }}
      ACCOUNT_ID_CLOUDFLARE: ${{ secrets.ACCOUNT_ID_CLOUDFLARE }}
      DATABASE_ID_CLOUDFLARE: ${{ secrets.DATABASE_ID_CLOUDFLARE }}

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
      
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install
      
      - name: Ejecutar Puppeteer
        run: npm run start